# GPT-5 Mini (High Effort)

wandb:
  run_name: "gpt-5-mini-2025-08-07: high-effort"

metadata:
  release_date: "2025-08-07"
  size_category: null
  model_size: null
  context_window: 400000
  max_output_tokens: 128000

model:
  name: gpt-5-mini-2025-08-07
  client: openai
  provider: openai
  api_key_env: OPENAI_API_KEY

  params:
    max_tokens: 128000
    temperature: 1
    reasoning_effort: high

benchmarks:
  bfcl:
    use_native_tools: true
  swebench_verified_official_80:
    max_tokens: 128000
