# o4-mini

wandb:
  run_name: "o4-mini-2025-04-16"

metadata:
  release_date: "2025-04-16"
  size_category: null
  model_size: null
  context_window: 200000
  max_output_tokens: 100000

model:
  name: o4-mini-2025-04-16
  client: openai
  provider: openai
  api_key_env: OPENAI_API_KEY

  params:
    max_tokens: 100000
    temperature: 1

benchmarks:
  bfcl:
    use_native_tools: true
  swebench_verified_official_80:
    max_tokens: 100000
