wandb:
  params:
    run_name: "claude-sonnet-4-5-20250929: high-effort"

model:
  name: litellm
  params:
    model_name: claude-sonnet-4-5-20250929
    provider: anthropic
    batch_size: 32
    max_tokens: 64000
    temperature: 1.0
    reasoning_effort: "high"
  release_date: "2025-09-29"
  model_size: None
  size_category: None