model:
  name: litellm
  params:
    model_name: claude-sonnet-4-5-20250929
    provider: anthropic
    batch_size: 32
    max_tokens: 1024
    temperature: 0.0
  release_date: "2025-09-29"
  model_size: None
  size_category: unknown


mrcr_2_needles:
  model_params:
    max_tokens: 32768