wandb:
  params:
    run_name: "claude-haiku-4-5-20251001: low-effort"

model:
  name: litellm
  params:
    model_name: claude-haiku-4-5-20251001
    provider: anthropic
    batch_size: 32
    max_tokens: 64000
    temperature: 1.0
    reasoning_effort: "low"
  release_date: "2025-10-01"
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 32000
    temperature: 1.0
    model_name: claude-haiku-4-5-20251001-FC