wandb:
  params:
    run_name: "claude-haiku-4-5-20251001: high-effort"

model:
  name: litellm
  params:
    model_name: claude-haiku-4-5-20251001
    provider: anthropic
    batch_size: 32
    max_tokens: 64000
    temperature: 
    reasoning_effort: "high"
  release_date: "2025-10-01"
  model_size: None
  size_category: None