wandb:
  run_name: "openai/gpt-oss-120b" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: openrouter
batch_size: 32 # vllmは256, apiは32を推奨

model:
  base_url: "https://openrouter.ai/api/v1"
  pretrained_model_name_or_path: "openai/gpt-oss-120b" #if you use openai api, put the name of model
  size_category: "30B≤"
  size: 117000000000
  release_date: "8/6/2025"

# generator:
#   extra_body:
#     provider:
#       order:
#         - "groq"
#         - "novita"
#         - "fireworks"
#     reasoning:
#       exclude: false
#       max_tokens: 100000