wandb:
  run_name: "upstage/solar-pro-250422" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: upstage
batch_size: 32 # vllmは256, apiは32を推奨
inference_interval: 2 # seconds

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "solar-pro-250422" #if you use openai api, put the name of model
  chat_template: null
  size_category: "api"
  size: null
  release_date: "4/22/2025"
