wandb:
  run_name: "xai/grok-2-latest" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: xai
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "grok-2-latest" #if you use openai api, put the name of model
  size_category: "30B≤"
  base_url: "https://api.x.ai/v1"
  size: 
  release_date: "2/18/2025"