wandb:
  run_name: "42dot/42dot_LLM-SFT-1.3B" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "42dot/42dot_LLM-SFT-1.3B" #if you use openai api, put the name of model
  chat_template: "42dot/42dot_LLM-SFT-1.3B"
  size_category: "<10B"
  size: null
  release_date: "7/1/2024"