wandb:
  run_name: "meta-llama/Llama-3.2-3B-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/Llama-3.2-3B-Instruct" #if you use openai api, put the name of model
  chat_template: "meta-llama/Llama-3.2-3B-Instruct"
  size_category: "<10B"
  size: 3210000000
  release_date: "9/25/2024"
  max_model_len: 2500