wandb:
  run_name: "JinValentine/Jonathan-aLLM-Meta-Llama-3-8B-Instruct-Korean-v1.0" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 128 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "JinValentine/Jonathan-aLLM-Meta-Llama-3-8B-Instruct-Korean-v1.0" #if you use openai api, put the name of model
  chat_template: "JinValentine/Jonathan-aLLM-Meta-Llama-3-8B-Instruct-Korean-v1.0"
  size_category: "<10B"
  size: 
  release_date: "7/1/2024"