wandb:
  run_name: "google/gemma-2-2b-it" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 128 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "google/gemma-2-2b-it" #if you use openai api, put the name of model
  chat_template: "google/gemma-2-2b-it"
  size_category: "<10B"
  size: 2610000000
  release_date: "8/1/2024"