wandb:
  run_name: "K-intelligence/Midm-2.0-Base-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: "friendliai"
batch_size: 32 # vllmは256, apiは32を推奨

model:
  pretrained_model_name_or_path: "K-intelligence/Midm-2.0-Base-Instruct" #if you use openai api, put the name of model
  size_category: "10B≤ <30B"
  size: 11500000000
  release_date: "7/3/2025"
  max_model_len: 2500
