wandb:
  run_name: "google/gemma-3-1b-it" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "google/gemma-3-1b-it" #if you use openai api, put the name of model
  chat_template: "google/gemma-3-1b-it"
  size_category: "<10B"
  size: 1000000000
  release_date: "3/12/2025"
  max_model_len: 2500