wandb:
  run_name: "yanolja/EEVE-Korean-Instruct-10.8B-v1.0" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "yanolja/EEVE-Korean-Instruct-10.8B-v1.0" #if you use openai api, put the name of model
  chat_template: "yanolja/EEVE-Korean-Instruct-10.8B-v1.0"
  size_category: "10B≤ <30B"
  size: 10800000000
  release_date: "1/1/2024"
  max_model_len: 2500