wandb:
  run_name: "LGAI-EXAONE/EXAONE-Deep-7.8B" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  pretrained_model_name_or_path: "LGAI-EXAONE/EXAONE-Deep-7.8B" #if you use openai api, put the name of model
  chat_template: "LGAI-EXAONE/EXAONE-Deep-7.8B"
  size_category: "<10B"
  size: 7820000000
  release_date: "5/18/2025"
  max_model_len: 2500
