wandb:
  run_name: "kakaocorp/kanana-1.5-32.5b-instruct-2504" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: kakaocorp_private
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "kanana-1.5-32.5b-instruct-2504" #if you use openai api, put the name of model
  size_category: "api"
  size: 32500000000
  release_date: "5/4/2025"
  base_url: "http://34.61.236.68:8000/v1"

generator:
  temperature: 0.0
  max_tokens: 512

