wandb:
  run_name: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct" #if you use openai api, put the name of model
  chat_template: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
  size_category: "<10B"
  size: null
  release_date: "8/7/2024"
  max_model_len: 2500