wandb:
  run_name: "google/gemini-2.5-flash" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthropic", "google", "cohere", "vllm", "mistral", "bedrock"
api: openrouter
batch_size: 32 # vllmは256, apiは32を推奨
inference_interval: 1 # seconds

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "gemini-2.5-flash" #if you use openai api, put the name of model
  size_category: "api"
  size: null
  release_date: "6/17/2025"

generator:
  max_tokens: 128
  reasoning_effort: "high"