wandb:
  run_name: "openai/o1-mini-2024-09-12" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: openai
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "o1-mini-2024-09-12" #if you use openai api, put the name of model
  size_category: "api"
  size: null
  release_date: "9/12/2024"

generator:
  top_p: 1.0
  # top_k: 0
  temperature: 1.0
  # repetition_penalty: 1.0
  max_tokens: 128