wandb:
  run_name: "K-intelligence/Midm-2.0-Mini-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "K-intelligence/Midm-2.0-Mini-Instruct" #if you use openai api, put the name of model
  chat_template: "K-intelligence/Midm-2.0-Mini-Instruct"
  size_category: "<10B"
  size: 231000000
  release_date: "7/4/2025"
  max_model_len: 3000