wandb:
  run_name: "Edentns/DataVortexS-10.7B-dpo-v1.11" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 128 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Edentns/DataVortexS-10.7B-dpo-v1.11" #if you use openai api, put the name of model
  chat_template: "Edentns/DataVortexS-10.7B-dpo-v1.11"
  size_category: "10B≤ <30B"
  size: null
  release_date: "1/1/2024"