wandb:
  run_name: "Qwen/Qwen3-32B" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: "friendliai"
batch_size: 32 # vllmは256, apiは32を推奨

model:
  pretrained_model_name_or_path: "dephz04u40aojtj" #if you use openai api, put the name of model
  size_category: "30B≤"
  base_url: "https://api.friendli.ai/dedicated/v1"
  size: 32800000000
  release_date: "4/29/2025"
  max_model_len: 2500

# generator:
#   enable_thinking: False