wandb:
  run_name: "meta-llama/Llama-3.1-70B-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨
num_gpus: 4

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/Llama-3.1-70B-Instruct" #if you use openai api, put the name of model
  chat_template: "meta-llama/Llama-3.1-70B-Instruct"
  size_category: "30B≤"
  size: 
  release_date: "7/24/2024"
  max_model_len: 2500