model:
  name: litellm
  params:
    model_name: gpt-4o-2024-11-20
    provider: openai
    max_tokens: 16384
    temperature: 0.0
    batch_size: 32
  release_date: "2024-11-20"
  model_size: None
  size_category: unknown
