model:
  name: litellm
  params:
    model_name: gpt-4.1-2025-04-14
    provider: openai
    batch_size: 32
    max_tokens: 32768
    temperature: 0.3
  release_date: "2024-04-14"
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 32768
    model_name: gpt-4.1-2025-04-14-FC