model:
  name: litellm
  params:
    model_name: gpt-5-mini-2025-08-07
    provider: openai
    batch_size: 32
    max_completion_tokens: 1024
    temperature: 1
  release_date: "2025-08-07"
  model_size: None
  size_category: mini