model:
  name: litellm
  params:
    model_name: grok-4-fast-reasoning
    provider: xai
    max_tokens: 1024
    temperature: 0.0
    batch_size: 32
  release_date: "2025-07-09"
  model_size: None
  size_category: middle


# model:
#   name: openai
#   params:
#     model_name: grok-4-fast-reasoning
#     api_base: https://api.x.ai/v1
#     batch_size: 32
#     max_tokens: 1024
#     temperature: 0.0
#   release_date: "2025-07-09"