model:
  name: litellm
  params:
    model_name: grok-4-fast-non-reasoning
    provider: xai
    max_tokens: 1024
    temperature: 0.0
    batch_size: 32
  release_date: "2025-07-09"
  model_size: None
  size_category: middle


mrcr_2_needles:
  model_params:
    max_tokens: 32768