model:
  name: litellm
  params:
    model_name: o4-mini-2025-04-16
    provider: openai
    batch_size: 32
    temperature: 1.0
    max_completion_tokens: 2048
  release_date: "2025-04-16"
  model_size: None
  size_category: None

halluLens:
  model_params:
    max_tokens: 256
    temperature: 1.0

bfcl:
  model_params:
    max_tokens: 8096
    temperature: 1.0

swebench:
  model_params:
    max_tokens: 32768
    temperature: 1.0

mt_bench:
  model_params:
    max_tokens: 1024
    temperature: 1.0

komoral:
  model_params:
    max_tokens: 10
    temperature: 1.0

kobbq:
  model_params:
    max_tokens: 10
    temperature: 1.0

squad_kor_v1:
  model_params:
    max_tokens: 20
    temperature: 1.0

ifeval_ko:
  model_params:
    max_tokens: 2048
    temperature: 1.0

mrcr_2_needles:
  model_params:
    max_tokens: 65536
    temperature: 1.0

haerae_bench_v1_w_RC:
  model_params:
    max_tokens: 10
    temperature: 1.0

haerae_bench_v1_wo_RC:
  model_params:
    max_tokens: 10
    temperature: 1.0

korean_parallel_corpora:
  model_params:
    max_tokens: 1024
    temperature: 1.0

korean_hate_speech:
  model_params:
    max_tokens: 10
    temperature: 1.0

kmmlu:
  model_params:
    max_tokens: 2048
    temperature: 1.0
    
kmmlu_pro:
  model_params:
    max_tokens: 2048
    temperature: 1.0

kobalt_700_syntax:
  model_params:
    max_tokens: 2048
    temperature: 1.0

kobalt_700_semantic:
  model_params:
    max_tokens: 2048
    temperature: 1.0

aime2025:
  model_params:
    max_tokens: 1024
    temperature: 1.0

hrm8k:
  model_params:
    max_tokens: 1024
    temperature: 1.0

hle:
  model_params:
    max_tokens: 4096
    temperature: 1.0

arc_agi:
  model_params:
    max_tokens: 4096
    temperature: 1.0