model:
  name: openai
  params:
    model_name: qwen3-max-2025-09-23
    api_base: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
    batch_size: 32
    max_tokens: 1024
    temperature: 0.0
  release_date: "2025-09-23"
  model_size: None
  size_category: large