model:
  name: openai
  params:
    model_name: qwen-plus-2025-07-28
    api_base: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
    batch_size: 8
    max_tokens: 1024
    temperature: 0.0
  release_date: "2025-07-28"
  model_size: None
  size_category: middle