wandb:
  params:
    run_name: "google-gemma-3-4b-it"

model:
  name: litellm
  params:
    model_name: hosted_vllm/google/gemma-3-4b-it
    provider: hosted_vllm
    api_base: http://localhost:8011/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 16384
    num_gpus: 1
    port: 8011
    pretrained_model_name_or_path: "google/gemma-3-4b-it"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: None
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: google/gemma-3-4b-it

