wandb:
  params:
    run_name: k-intelligence-midm-2.0-base-instruct

model:
  name: litellm
  params:
    model_name: "K-intelligence/Midm-2.0-Base-Instruct"
    provider: hosted_vllm
    api_base: http://localhost:8007/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 32768
    num_gpus: 1
    port: 8007
    pretrained_model_name_or_path: "K-intelligence/Midm-2.0-Base-Instruct"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: "2025-07-04"
  model_size: 12000000000
  size_category: "Medium (10-30B)"

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: "K-intelligence/Midm-2.0-Base-Instruct"
