wandb:
  params:
    run_name: kakaocorp-kanana-1.5-8b-instruct-2505

model:
  name: litellm
  params:
    model_name: "kakaocorp/kanana-1.5-8b-instruct-2505"
    provider: hosted_vllm
    api_base: http://localhost:8016/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 32768
    num_gpus: 1
    port: 8016
    pretrained_model_name_or_path: "kakaocorp/kanana-1.5-8b-instruct-2505"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: None
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: kakaocorp-kanana-1.5-8b-instruct-2505
