# https://huggingface.co/LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct
wandb:
  params:
    run_name: lgai-exaone-exaone-3.0-7.8b-instruct

model:
  name: litellm
  params:
    model_name: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
    provider: hosted_vllm
    api_base: http://localhost:8033/v1
    batch_size: 8
    max_tokens: 1024
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 4096
    num_gpus: 1
    port: 8033
    pretrained_model_name_or_path: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: "2024-08-07"
  model_size: 7800000000
  size_category: "Small (<10B)"

bfcl:
  model_params:
    max_tokens: 1024
    temperature: 0.1
    model_name: "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
