wandb:
  params:
    run_name: "lgai-exaone-exaone-4.0-1.2b"

model:
  name: litellm
  params:
    model_name: "LGAI-EXAONE/EXAONE-4.0-1.2B"
    provider: hosted_vllm
    api_base: http://localhost:8002/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 65536
    num_gpus: 1
    port: 8002
    pretrained_model_name_or_path: "LGAI-EXAONE/EXAONE-4.0-1.2B"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: None
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: lgai-exaone-exaone-4.0-1.2b
