wandb:
  params:
    run_name: skt-a.x-3.1

model:
  name: litellm
  params:
    model_name: "skt/A.X-3.1"
    provider: hosted_vllm
    api_base: http://localhost:8100/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 32768
    num_gpus: 2
    port: 8100
    pretrained_model_name_or_path: "skt/A.X-3.1"
    tensor_parallel_size: 2
    trust_remote_code: true
  release_date: "2025-07-24"
  model_size: 35000000000
  size_category: "Large (30B<)"

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: "skt/A.X-3.1"
