wandb:
  params:
    run_name: "skt-a.x-4.0"

model:
  name: litellm
  params:
    model_name: hosted_vllm/skt/A.X-4.0
    provider: hosted_vllm
    api_base: http://localhost:8005/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 16384
    num_gpus: 2
    port: 8005
    pretrained_model_name_or_path: "skt/A.X-4.0"
    tensor_parallel_size: 2
    trust_remote_code: true
  release_date: None
  model_size: None
  size_category: None

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: skt/A.X-4.0
