wandb:
  params:
    run_name: trillionlabs-tri-7b

model:
  name: litellm
  params:
    model_name: "trillionlabs/Tri-7B"
    provider: hosted_vllm
    api_base: http://localhost:8027/v1
    batch_size: 8
    max_tokens: 8192
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 32768
    num_gpus: 1
    port: 8027
    pretrained_model_name_or_path: "trillionlabs/Tri-7B"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: "2025-07-22"
  model_size: 7000000000
  size_category: "Small (<10B)"

bfcl:
  model_params:
    max_tokens: 8192
    temperature: 0.1
    model_name: "trillionlabs/Tri-7B"
