wandb:
  params:
    run_name: trillionlabs-tri-21b

model:
  name: litellm
  params:
    model_name: "trillionlabs/Tri-21B"
    provider: hosted_vllm
    api_base: http://localhost:8028/v1
    batch_size: 8
    max_tokens: 1024
    temperature: 0.1
  vllm_params:
    batch_size: 16
    dtype: "auto"
    download_dir: "/dataset/models/huggingface/hub"
    max_model_len: 8192
    num_gpus: 1
    port: 8028
    pretrained_model_name_or_path: "trillionlabs/Tri-21B"
    tensor_parallel_size: 1
    trust_remote_code: true
  release_date: "2025-07-22"
  model_size: 21000000000
  size_category: "Medium (10â€“30B)"

bfcl:
  model_params:
    max_tokens: 1024
    temperature: 0.1
    model_name: "trillionlabs/Tri-21B"
