model:
  name: openai
  params:
    model_name: gemini-2.5-flash
    api_base: https://generativelanguage.googleapis.com/v1beta/openai/
    batch_size: 32
    max_tokens: 1024
    temperature: 0.0
  release_date: 2025-06-17