model:
  name: openai
  params:
    model_name: qwen-turbo-2025-04-28
    api_base: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
    batch_size: 8
    max_tokens: 1024
    temperature: 0.0
  release_date: "2025-04-28"